font_family Fira Code Nerd Font
font_features FiraCodeNerdFontComplete-Regular +ss01 +ss02 +ss03 +ss04 +ss05 +ss07 +ss08 +zero +onum

cursor_shape beam
cursor_blink_interval 1
window_padding_width 2 3
mouse_hide_wait 0
touch_scroll_multiplier 2.0
include ./tokyonight-night.conf
confirm_os_window_close 0
shell /usr/bin/nu
