#!/bin/sh

# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.
mainDisplay="Acer Technologies VG270U P 0x912094FE"
secondaryDisplay="Acer Technologies VG270 TEGEE0018512"
horizontalDisplay="AOC 2470W GGJGCHA013780"

exec kanshi default &
exec waybar &
exec swaybg -i ~/.wallpapers/zelda-full.jpg -m fill -o "${horizontalDisplay}" -m fill -i ~/.wallpapers/od_fuck_u_nvidia_green.png &
exec dunst &
exec spotify &
exec Obsidian --disable-gpu &

# Terminal
riverctl map normal Alt Return spawn foot

# Launcher
riverctl map normal Alt D spawn "wmenu-run -i -l 5"
riverctl map normal Alt P spawn "${HOME}/.config/scripts/powermenu.sh"

# Alt+Q to close the focused view
riverctl map normal Alt Q close

# Alt+Shift+E to exit river
riverctl map normal Alt+Shift E exit

# Alt+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Alt J focus-view next
riverctl map normal Alt K focus-view previous

# Alt+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Alt+Shift J swap next
riverctl map normal Alt+Shift K swap previous

# Alt+Period and Super+Comma to focus the next/previous output
riverctl map normal Alt Period focus-output right
riverctl map normal Alt Comma focus-output left

# Alt+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Alt+Shift Period send-to-output right
riverctl map normal Alt+Shift Comma send-to-output left

# Alt+Return to bump the focused view to the top of the layout stack
# riverctl map normal Alt Return zoom

# Alt+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Alt H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Alt L send-layout-cmd rivertile "main-ratio +0.05"

# Alt+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Alt+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Alt+Shift L send-layout-cmd rivertile "main-count -1"

# Alt + Left Mouse Button to move views
riverctl map-pointer normal Alt BTN_LEFT move-view

# Alt + Right Mouse Button to resize views
riverctl map-pointer normal Alt BTN_RIGHT resize-view

# Alt + Middle Mouse Button to toggle float
riverctl map-pointer normal Alt BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Alt+[1-9] to focus tag [0-8]
    riverctl map normal Alt $i set-focused-tags $tags

    # Alt+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Alt+Shift $i set-view-tags $tags

    # Alt+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Alt+Control $i toggle-focused-tags $tags

    # Alt+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Alt+Shift+Control $i toggle-view-tags $tags
done

# Alt+0 to focus all tags
# Alt+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Alt 0 set-focused-tags $all_tags
riverctl map normal Alt+Shift 0 set-view-tags $all_tags

# Alt+Space to toggle float
riverctl map normal Alt Space toggle-float

# Alt+F to toggle fullscreen
riverctl map normal Alt+Shift F toggle-fullscreen

# Alt+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Alt+Control Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Alt+Control Right send-layout-cmd rivertile "main-location right"
riverctl map normal Alt+Control Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Alt+Control Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Alt+F11 to enter passthrough mode
riverctl map normal Alt F11 enter-mode passthrough

# Alt+F11 to return to normal mode
riverctl map passthrough Alt F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'
done

# Set background and border color
riverctl border-color-focused 0x4dbdcb
riverctl border-color-unfocused 0x343e4f

riverctl set-cursor-warp on-output-change
riverctl focus-follows-cursor normal

# Set keyboard repeat rate
riverctl set-repeat 40 300
riverctl keyboard-layout de

riverctl rule-add -app-id "Firefox" output "${secondaryDisplay}"
riverctl rule-add -app-id "foot" output "${mainDisplay}"
riverctl rule-add -app-id "Spotify" output "${horizontalDisplay}"
riverctl rule-add -app-id "obsidian" output "${horizontalDisplay}"

riverctl rule-add -app-id "Firefox" -title "Library" float

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

# The scratchpad will live on an unused tag. Which tags are used depends on your
# config, but rivers default uses the first 9 tags.
scratch_tag=$((1 << 20 ))

# Toggle the scratchpad with Super+P
riverctl map normal Super P toggle-focused-tags ${scratch_tag}

# Send windows to the scratchpad with Super+Shift+P
riverctl map normal Super+Shift P set-view-tags ${scratch_tag}

# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}

# The scratchpad will live on an unused tag. Which tags are used depends on your
# config, but rivers default uses the first 9 tags.
scratch_tag=$((1 << 20 ))

# Toggle the scratchpad with Super+P
riverctl map normal Super P toggle-focused-tags ${scratch_tag}

# Send windows to the scratchpad with Super+Shift+P
riverctl map normal Super+Shift P set-view-tags ${scratch_tag}

# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}
