theme = "gruvbox"

[editor]
bufferline = "always"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
right = ["diagnostics", "file-encoding", "selections", "position"]

[editor.file-picker]
hidden = false

[keys.normal."ö"]
d = "goto_prev_diag"
D = "goto_first_diag"
f = "goto_prev_function"
t = "goto_prev_class"
a = "goto_prev_parameter"
c = "goto_prev_comment"
T = "goto_prev_test"
p = "goto_prev_paragraph"
g = "goto_prev_change"
G = "goto_first_change"
"space" = "add_newline_above"

[keys.normal."ä"]
d = "goto_next_diag"
D = "goto_last_diag"
f = "goto_next_function"
t = "goto_next_class"
a = "goto_next_parameter"
c = "goto_next_comment"
T = "goto_next_test"
p = "goto_next_paragraph"
g = "goto_next_change"
G = "goto_last_change"
"space" = "add_newline_below"
