;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[global/wm]
include-file = ~/.config/polybar/colors
include-file = ~/.config/polybar/modules/separators
include-file = ~/.config/polybar/modules/modules

[bar/main]
width = 100%
height = 25px

; dpi = 96

background = ${color.bg}
foreground = ${color.fg}

line-size = 20
line-color = ${color.bg}

;border-size = 5px
border-color = ${color.bg}

padding-left = 0
padding-right = 0

font-0 = Fira Code Nerd Font:size=12;2
font-1 = Fira Code Nerd Font:size=19;4

modules-left = workspaces
modules-center = date
modules-right = cpu-temp cpu ram audio

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
module-margin-right = 0
module-margin-left = 0


tray-position = right

wm-restack = i3

[settings]
screenchange-reload = true

